Ft wallet funding
devcareer/team-fintech-backend pull request #40
Opened 2022-12-02 15:31 UTC by ToluwaDavid

Wallet funding feature that enables user fund their wallet

2022-12-06 10:37 UTC, bright258 commented
Please add a description to your pull request on how I can test it. You can look at other pull requests if you need a sample.

2022-12-06 15:31 UTC, kelue requested changes

2022-12-06 15:31 UTC, kelue commented on src/controllers/walletControllers.js
> +async function createWallet(req, res, next) {
There's no need to change this because it's correct syntax

2022-12-06 15:31 UTC, kelue commented on src/controllers/walletControllers.js
> +    const fundReference = `transfer-${Date.now()}`;
Date now is not a robust transaction reference. What happens if multiple transactions happen at the same time. Better to use a uuid then you can attached a date now to it if you want, but I would advise that you did not

2022-12-06 15:31 UTC, kelue commented on src/controllers/walletControllers.js
> +    const callbackUrl = 'https://webhook.site/74e008b8-e302-406c-84bd-dd19d400d8cf'; // Page to redirect users to after funding their wallet
call back url should not be hard coded, it should be a environmental variable

2022-12-06 15:45 UTC, kelue commented on src/controllers/walletControllers.js
> +async function createWallet(req, res, next) {
The arrow function and function declaration do the same thing

2022-12-11 17:17 UTC, closed without merging

2022-12-11 17:18 UTC, ToluwaDavid commented
Closed, working and updating the feature